apiVersion: apps/v1
kind: Deployment
metadata:
  name: ordermanage
  labels:
    app: ordermanage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ordermanage
  template:
    metadata:
      labels:
        app: ordermanage
    spec:
      containers:
        - name: ordermanage
          image: username/ordermanage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5